name: Repo2 Trigger

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Trigger website rebuild
        run: ./.github/scripts/build_website.sh
        env:
          REPO2_BUILD: ${{ secrets.github_token }}
