name: Repo2 Trigger

on:
  push:
    paths:
      - 'documentation/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website rebuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: curl --version